export const Tags = {
  Oneshot: "Oneshot",
  Thriller: "Thriller",
  "Award Winning": "Award Winning",
  Reincarnation: "Reincarnation",
  "Sci-Fi": "Sci-Fi",
  "Time Travel": "Time Travel",
  Genderswap: "Genderswap",
  "Traditional Games": "Traditional Games",
  "Official Colored": "Official Colored",
  Historical: "Historical",
  Monsters: "Monsters",
  Action: "Action",
  Demons: "Demons",
  Psychological: "Psychological",
  Ghosts: "Ghosts",
  Animals: "Animals",
  "Long Strip": "Long Strip",
  Romance: "Romance",
  Ninja: "Ninja",
  Comedy: "Comedy",
  Mecha: "Mecha",
  Anthology: "Anthology",
  "Boys' Love": "Boys' Love",
  Incest: "Incest",
  Crime: "Crime",
  Survival: "Survival",
  Zombies: "Zombies",
  "Reverse Harem": "Reverse Harem",
  Sports: "Sports",
  Superhero: "Superhero",
  "Martial Arts": "Martial Arts",
  "Fan Colored": "Fan Colored",
  Samurai: "Samurai",
  "Magical Girls": "Magical Girls",
  Mafia: "Mafia",
  Adventure: "Adventure",
  "Self-Published": "Self-Published",
  "Virtual Reality": "Virtual Reality",
  "Office Workers": "Office Workers",
  "Video Games": "Video Games",
  "Post-Apocalyptic": "Post-Apocalyptic",
  "Sexual Violence": "Sexual Violence",
  Crossdressing: "Crossdressing",
  Magic: "Magic",
  "Girls' Love": "Girls' Love",
  Harem: "Harem",
  Military: "Military",
  Wuxia: "Wuxia",
  Isekai: "Isekai",
  "4-Koma": "4-Koma",
  Doujinshi: "Doujinshi",
  Philosophical: "Philosophical",
  Gore: "Gore",
  Drama: "Drama",
  Medical: "Medical",
  "School Life": "School Life",
  Horror: "Horror",
  Fantasy: "Fantasy",
  Villainess: "Villainess",
  Vampires: "Vampires",
  Delinquents: "Delinquents",
  "Monster Girls": "Monster Girls",
  Shota: "Shota",
  Police: "Police",
  "Web Comic": "Web Comic",
  "Slice of Life": "Slice of Life",
  Aliens: "Aliens",
  Cooking: "Cooking",
  Supernatural: "Supernatural",
  Mystery: "Mystery",
  Adaptation: "Adaptation",
  Music: "Music",
  "Full Color": "Full Color",
  Tragedy: "Tragedy",
  Gyaru: "Gyaru",
} as const;

export type Tags = (typeof Tags)[keyof typeof Tags];
